services:
  promptlayer-proxy:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: promptlayer-proxy
    restart: always
    ports:
      - "3001:3000"
    environment:
      - ACCOUNTS=email1:password1,...
      - AUTH_TOKEN=sk-123456